//Version Info .

#ifndef _M_VER_
#define _M_VER_

//Icon Files .
#define VIconFileName "ICON1.ICO"

//File Version Number .
#define VFileVersion "0.0"

//Product Version Number .
#define VProductVersion "0.95"

//Other Version Details
#define VProductName "AfterBurn"
#define VCompanyName "ODE"
#define VLegalCopyright "Copyrights © Karthik Kumar V & Nikhil Karnad"
#define VLegalTrademarks "None"
#define VFileDescription "A Video Game"
#define VComments "None"
#define VInternalName "Can't Say"
#define VOriginalFilename "Can't Say"

//Language Details
#define VCountry 0x409
#define VLanguage 1200

#endif //_M_VER_

